// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmbprkpikjrctutpqpaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtYnBya3Bpa2pyY3R1dHBxcGFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NzM4MDQsImV4cCI6MjA3MjA0OTgwNH0.yimhF7gv8D8TG1UjW7X_ZcxNY7rUUYhLilkyKPX94Uo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});